name: beans
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  ffi: ^1.1.2
  meta: ^1.7.0
  yaml: ^3.1.1

dev_dependencies:
  pedantic: ^1.10.0
